name: CI

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a Slow Job
        run: sleep 600
