name: CI

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Workflow
        run: "true"
